export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        page: 'rgb(var(--sl-page) / <alpha-value>)',
        surface: 'rgb(var(--sl-surface) / <alpha-value>)',
        content: 'rgb(var(--sl-content) / <alpha-value>)',
        'content-muted': 'rgb(var(--sl-content-muted) / <alpha-value>)',
        'on-dark': 'rgb(var(--sl-on-dark) / <alpha-value>)',
        'on-light': 'rgb(var(--sl-on-light) / <alpha-value>)',
        brand: 'rgb(var(--sl-brand) / <alpha-value>)',
        'brand-soft': 'rgb(var(--sl-brand-soft) / <alpha-value>)',
        'brand-hover': 'rgb(var(--sl-brand-hover) / <alpha-value>)',
        'brand-navy': 'rgb(var(--sl-brand-navy) / <alpha-value>)',
        'brand-focus': 'rgb(var(--sl-brand-focus) / <alpha-value>)',
        'brand-text': 'rgb(var(--sl-brand-text) / <alpha-value>)',
        action: 'rgb(var(--sl-action) / <alpha-value>)',
        'action-hover': 'rgb(var(--sl-action-hover) / <alpha-value>)',
        'action-pale': 'rgb(var(--sl-action-pale) / <alpha-value>)',
        'action-soft': 'rgb(var(--sl-action-soft) / <alpha-value>)',
        'action-bright': 'rgb(var(--sl-action-bright) / <alpha-value>)',
        'action-deep': 'rgb(var(--sl-action-deep) / <alpha-value>)',
        glass: 'rgb(var(--sl-glass) / <alpha-value>)',
        overlay: 'rgb(var(--sl-overlay) / <alpha-value>)',
        'dark-surface': 'rgb(var(--sl-dark-surface) / <alpha-value>)',
        'dark-elevated': 'rgb(var(--sl-dark-elevated) / <alpha-value>)',
        'dark-muted': 'rgb(var(--sl-dark-muted) / <alpha-value>)',
        'dark-strong': 'rgb(var(--sl-dark-strong) / <alpha-value>)',
        'content-soft': 'rgb(var(--sl-content-soft) / <alpha-value>)',
        'content-subtle': 'rgb(var(--sl-content-subtle) / <alpha-value>)',
        'border-light': 'rgb(var(--sl-border-light) / <alpha-value>)',
        neutral: 'rgb(var(--sl-neutral) / <alpha-value>)',
        success: 'rgb(var(--sl-success) / <alpha-value>)',
        'success-base': 'rgb(var(--sl-success-base) / <alpha-value>)',
        'success-bright': 'rgb(var(--sl-success-bright) / <alpha-value>)',
        'success-soft': 'rgb(var(--sl-success-soft) / <alpha-value>)',
        'success-deep': 'rgb(var(--sl-success-deep) / <alpha-value>)',
        warning: 'rgb(var(--sl-warning) / <alpha-value>)',
        'warning-base': 'rgb(var(--sl-warning-base) / <alpha-value>)',
        'warning-bright': 'rgb(var(--sl-warning-bright) / <alpha-value>)',
        'warning-soft': 'rgb(var(--sl-warning-soft) / <alpha-value>)',
        'warning-pale': 'rgb(var(--sl-warning-pale) / <alpha-value>)',
        danger: 'rgb(var(--sl-danger) / <alpha-value>)',
        'danger-base': 'rgb(var(--sl-danger-base) / <alpha-value>)',
        'danger-bright': 'rgb(var(--sl-danger-bright) / <alpha-value>)',
        'danger-soft': 'rgb(var(--sl-danger-soft) / <alpha-value>)',
        'danger-pale': 'rgb(var(--sl-danger-pale) / <alpha-value>)',
        info: 'rgb(var(--sl-info) / <alpha-value>)',
        'map-available': 'rgb(var(--sl-map-available) / <alpha-value>)',
        'map-unavailable': 'rgb(var(--sl-map-unavailable) / <alpha-value>)',
        'chart-primary': 'rgb(var(--sl-chart-primary) / <alpha-value>)',
        'chart-hover': 'rgb(var(--sl-chart-hover) / <alpha-value>)',
        'chart-violet': 'rgb(var(--sl-chart-violet) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
