export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        page: 'rgb(var(--sl-page) / <alpha-value>)',
        surface: 'rgb(var(--sl-surface) / <alpha-value>)',
        content: 'rgb(var(--sl-content) / <alpha-value>)',
        'content-muted': 'rgb(var(--sl-content-muted) / <alpha-value>)',
        'on-dark': 'rgb(var(--sl-on-dark) / <alpha-value>)',
        'on-light': 'rgb(var(--sl-on-light) / <alpha-value>)',
        brand: 'rgb(var(--sl-brand) / <alpha-value>)',
        'brand-soft': 'rgb(var(--sl-brand-soft) / <alpha-value>)',
        'brand-navy': 'rgb(var(--sl-brand-navy) / <alpha-value>)',
        'brand-focus': 'rgb(var(--sl-brand-focus) / <alpha-value>)',
        'brand-text': 'rgb(var(--sl-brand-text) / <alpha-value>)',
        action: 'rgb(var(--sl-action) / <alpha-value>)',
        'action-hover': 'rgb(var(--sl-action-hover) / <alpha-value>)',
        glass: 'rgb(var(--sl-glass) / <alpha-value>)',
        overlay: 'rgb(var(--sl-overlay) / <alpha-value>)',
        'dark-surface': 'rgb(var(--sl-dark-surface) / <alpha-value>)',
        'dark-elevated': 'rgb(var(--sl-dark-elevated) / <alpha-value>)',
        'border-light': 'rgb(var(--sl-border-light) / <alpha-value>)',
        neutral: 'rgb(var(--sl-neutral) / <alpha-value>)',
        success: 'rgb(var(--sl-success) / <alpha-value>)',
        warning: 'rgb(var(--sl-warning) / <alpha-value>)',
        danger: 'rgb(var(--sl-danger) / <alpha-value>)',
        info: 'rgb(var(--sl-info) / <alpha-value>)',
        'map-available': 'rgb(var(--sl-map-available) / <alpha-value>)',
        'map-unavailable': 'rgb(var(--sl-map-unavailable) / <alpha-value>)',
        'chart-primary': 'rgb(var(--sl-chart-primary) / <alpha-value>)',
        'chart-hover': 'rgb(var(--sl-chart-hover) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
