  backup/feature-test-20260905[m
* [32mdevelop[m
  feature/a_propos_rgpd[m
  feature/admin_back_office[m
  feature/admin_bateaux[m
  feature/admin_commentaire[m
  feature/admin_document[m
  feature/admin_log[m
  feature/admin_port[m
  feature/admin_resa[m
  feature/admin_transaction[m
  feature/admin_utilisateur[m
  feature/admin_vue_spectateur[m
  feature/auth_gestion[m
  feature/back_reservation[m
  feature/back_reservation_historique[m
  feature/back_reservation_loc_reserv[m
  feature/back_reservation_session[m
  feature/back_reservation_tunel[m
  feature/back_reservation_verif_dispo[m
  feature/commentaire_publication[m
  feature/compte_desactivation_suppression[m
  feature/compte_profil[m
  feature/config_sauvegarde_bdd[m
  feature/connexion[m
  feature/contact[m
  feature/contact_form[m
  feature/cookies[m
  feature/criptage_doc[m
  feature/cron[m
  feature/dashboard[m
  feature/dashboard_locataire[m
  feature/dashboard_locataire_compte[m
  feature/dashboard_locataire_document[m
  feature/dashboard_locataire_favoris[m
  feature/dashboard_locataire_resarvation[m
  feature/dashboard_proprietaire[m
  feature/dashboard_proprietaire_bateau[m
  feature/dashboard_proprietaire_compte[m
  feature/dashboard_proprietaire_documents[m
  feature/dashboard_proprietaire_form_bateau[m
  feature/dashboard_proprietaire_resarvation[m
  feature/dashboard_proprietaire_revenue[m
  feature/deploiement[m
  feature/deploiement_sigterm[m
  feature/facture[m
  feature/gestion_route[m
  feature/inscription[m
  feature/mdp_oublie[m
  feature/messagerie[m
  feature/middleware[m
  feature/page_produit[m
  feature/paiement[m
  feature/paiement_remboursement_stripe[m
  feature/paiement_stripe[m
  feature/paiement_webhook_stripe_connect[m
  feature/postman[m
  feature/refacto[m
  feature/seo[m
  feature/test[m
  feature/test-couverture[m
  feature/update_photo_profil[m
  feature/upload_doc[m
  fix/admin_validation_post[m
  fix/compte_desactivation_suppression[m
  fix/correction_deploiment[m
  fix/csrf[m
  fix/dashboard[m
  fix/dashboard_style[m
  fix/deploiement[m
  fix/env-secrets[m
  fix/front[m
  fix/mail[m
  fix/paiement_document[m
  fix/performance_catalogue[m
  fix/proprietaire_locatire_profil[m
  fix/seeds[m
  fix/tunnel_connexion[m
  initialisation_bdd[m
  master[m
  salimou[m
  style/mail_message[m
  style/refonte[m
  style/responsive-dashboards[m
  style/tunnel_connexion_inscription[m
  test/local[m
