import crypto from 'crypto';
import csrf from 'csurf';
import { getRuntimeEnvironment } from '../config/appConfig.js';
import { normalizeRequestOrigin } from '../utils/corsSecurity.js';

export const CSRF_COOKIE_NAME = 'sl_csrf';
export const CSRF_HEADER_NAME = 'X-CSRF-Token';
export const CSRF_TOKEN_REQUIRED_CODE = 'CSRF_TOKEN_REQUIRED';
export const CSRF_TOKEN_INVALID_CODE = 'CSRF_TOKEN_INVALID';
export const CSRF_SAFE_METHODS = Object.freeze(['GET', 'HEAD', 'OPTIONS']);

const CSRF_COOKIE_TTL_SECONDS = 7 * 24 * 60 * 60;
const CSRF_SIGNING_CONTEXT = 'sailingloc:csrf-cookie:v1';

function isProductionLike(environment) {
  return ['production', 'staging'].includes(
    String(environment || getRuntimeEnvironment())
      .trim()
      .toLowerCase()
  );
}

export function deriveCsrfCookieSigningSecret(jwtSecret) {
  const configuredSecret = String(jwtSecret || '').trim();
  const keyMaterial = configuredSecret || crypto.randomBytes(32);
  return crypto.createHmac('sha256', keyMaterial).update(CSRF_SIGNING_CONTEXT).digest('hex');
}

// The maintained csurf fork uses cookie.serialize, whose maxAge unit is seconds.
export function csrfCookieOptions(environment = getRuntimeEnvironment()) {
  const productionLike = isProductionLike(environment);
  return {
    key: CSRF_COOKIE_NAME,
    signed: true,
    httpOnly: true,
    secure: productionLike,
    sameSite: productionLike ? 'strict' : 'lax',
    path: '/api',
    maxAge: CSRF_COOKIE_TTL_SECONDS,
  };
}

export function csrfRequestToken(req) {
  const token = req.get(CSRF_HEADER_NAME);
  return typeof token === 'string' ? token : '';
}

// Public requests and bearer-only clients do not carry the ambient refresh cookie.
export function ignoreRequestWithoutRefreshCookie(req) {
  return !req.cookies?.sl_refresh;
}

// Convenience factory for isolated apps/tests. The production server calls
// csrf() itself so CodeQL can directly identify the recognized guard.
export function createCsrfProtection({ environment = getRuntimeEnvironment() } = {}) {
  return csrf({
    cookie: csrfCookieOptions(environment),
    ignoreMethods: CSRF_SAFE_METHODS,
    ignoreRequest: ignoreRequestWithoutRefreshCookie,
    value: csrfRequestToken,
  });
}

function canExposeToken(req, trustedOrigins) {
  const requestOrigin = normalizeRequestOrigin(req.get('origin'));
  return Boolean(requestOrigin && trustedOrigins.has(requestOrigin));
}

function exposeToken(req, res, trustedOrigins) {
  if (!canExposeToken(req, trustedOrigins)) return;
  res.setHeader(CSRF_HEADER_NAME, req.csrfToken());
}

export function createCsrfTokenExposure({ allowedOrigins = new Set() } = {}) {
  const trustedOrigins = new Set(allowedOrigins);
  return function exposeCsrfToken(req, res, next) {
    try {
      exposeToken(req, res, trustedOrigins);
      return next();
    } catch (error) {
      return next(error);
    }
  };
}

// Translate the library error to the stable API codes understood by Axios.
// Legacy unsigned sl_csrf cookies get one bootstrap retry and are overwritten
// by the signed secret cookie generated by the maintained middleware.
export function createCsrfErrorHandler({ allowedOrigins = new Set() } = {}) {
  const trustedOrigins = new Set(allowedOrigins);
  return function handleCsrfError(error, req, res, next) {
    if (error?.code !== 'EBADCSRFTOKEN') return next(error);

    try {
      exposeToken(req, res, trustedOrigins);
    } catch (tokenError) {
      return next(tokenError);
    }

    const submittedToken = csrfRequestToken(req);
    const hasLegacyUnsignedCookie = Boolean(
      req.cookies?.[CSRF_COOKIE_NAME] && !req.signedCookies?.[CSRF_COOKIE_NAME]
    );
    const tokenRequired = !submittedToken || hasLegacyUnsignedCookie;

    return res.status(403).json({
      message: tokenRequired ? 'Jeton CSRF requis.' : 'Jeton CSRF invalide.',
      code: tokenRequired ? CSRF_TOKEN_REQUIRED_CODE : CSRF_TOKEN_INVALID_CODE,
    });
  };
}
